version: '3'
services:
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ['5432:5432']
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
